//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            Configuration.LazyLoadingEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<ReceiptItem> ReceiptItems { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<vReceiptItemsSummary> vReceiptItemsSummaries { get; set; }
        public virtual DbSet<vSupplierItem> vSupplierItems { get; set; }
        public virtual DbSet<vReceiptItem> vReceiptItems { get; set; }
        public virtual DbSet<PackageType> PackageTypes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<vReceiptSummary> vReceiptSummaries { get; set; }
        public virtual DbSet<vSupplierSummary> vSupplierSummaries { get; set; }
    
        public virtual ObjectResult<spReceiptSummary_Result> spReceiptSummary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReceiptSummary_Result>("spReceiptSummary");
        }
    }
}
