//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string companyName { get; set; }
        public string companyHeaderName { get; set; }
        public string receiptListDefaultDateRange { get; set; }
        public Nullable<bool> receiptItemConfirmDeletion { get; set; }
        public Nullable<bool> gblShowPermanentDeleteAuthUsers { get; set; }
        public string companyAddress { get; set; }
        public string companyPhone { get; set; }
        public string companyPhone2 { get; set; }
        public Nullable<bool> gblShowTimeOfDatetimeRange { get; set; }
    }
}
