//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ReceiptItems = new HashSet<ReceiptItem>();
        }
    
        public int itemId { get; set; }
        public string itemName { get; set; }
        public string itemPackage { get; set; }
        public string itemCategory { get; set; }
        public System.DateTime createdAt { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> modifiedAt { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<double> itemPackageDeposit { get; set; }
        public Nullable<double> itemFreight { get; set; }
        public Nullable<double> itemLandingCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptItem> ReceiptItems { get; set; }
        public virtual PackageType PackageType { get; set; }
    }
}
