//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptItem
    {
        public int receiptId { get; set; }
        public int itemId { get; set; }
        public string itemPackage { get; set; }
        public short itemQnty { get; set; }
        public double itemCost { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> modifiedAt { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<short> itemPackageCount { get; set; }
        public Nullable<double> itemPackageDeposit { get; set; }
        public Nullable<double> itemFreight { get; set; }
        public Nullable<double> itemLandingCost { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual PackageType PackageType { get; set; }
    }
}
