//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReceiptItemsSummary
    {
        public int receiptId { get; set; }
        public Nullable<int> itemsCount { get; set; }
        public Nullable<double> totalCost { get; set; }
    }
}
