//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReceiptSummary
    {
        public int receiptId { get; set; }
        public int supplierId { get; set; }
        public string supplierName { get; set; }
        public Nullable<System.DateTime> receiptDate { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> modifiedAt { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<int> itemsCount { get; set; }
        public Nullable<double> totalCost { get; set; }
    }
}
